name: venv
channels:
  - conda-forge
  - defaults
  - mathieu
dependencies:
  - jupyterlab>=3.5.0
  - nodejs>=15.14.0
  - yarn>=1.22.19
  - python>=3.8
  - tinydb
  - pygithub
  - tornado
  - notebook
  - pyyaml
  - nbformat
  - autopep8
  - Jinja2
  - distro
  - requests
  - colorhash
  - pyflakes
    
    
