name: Docker Image CI

on:
  push:
    tags:
      - '*'
      
env:
  TAG: "miniconda3-naavre"
  DOCKERHUB_IMAGE_ID: "qcdis/"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      run: |
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        echo $VERSION
      
    - uses: whoan/docker-build-with-cache-action@v5
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        image_name: qcdis:miniconda3-naavre
        image_tag: ,latest
        push_git_tag: true
    
